[package]
name = "kgd"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
authors.workspace = true

[[bin]]
name = "kgd"
path = "src/main.rs"

[dependencies]
serenity = { workspace = true }
tokio = { workspace = true }
anyhow = { workspace = true }
kgd-config = { path = "../config" }
kgd-core = { path = "../core" }
